# Generated by Django 2.0.3 on 2018-04-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
