# Generated by Django 2.0.3 on 2018-04-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180427_1253'),
        ('billing', '0002_auto_20180427_1306'),
    ]

    operations = [
    ]
