# Generated by Django 2.0.3 on 2018-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
