# Generated by Django 2.0.3 on 2018-04-05 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180404_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
