# Generated by Django 2.0.3 on 2018-04-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_timecreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timecreate',
            new_name='timestamp',
        ),
    ]
